import { CONTRACTS } from "./contracts";

export const BIST100_TICKERS = [
  "AEFES", "AKBNK", "AKSA", "AKSEN", "ALARK", "ANSGR", "ARCLK", "ASELS", "ASTOR", "BIMAS",
  "BRSAN", "BRYAT", "BTCIM", "CCOLA", "CIMSA", "DOAS", "DOHOL", "ECILC", "EKGYO", "ENKAI",
  "EREGL", "FENER", "FROTO", "GARAN", "GSRAY", "GUBRF", "TURSG", "HALKB", "HEKTS", "IPEKE",
  "ISCTR", "ISMEN", "KCHOL", "KOZAA", "KOZAL", "KRDMD", "MGROS", "OTKAR", "PETKM", "SAHOL",
  "SARKY", "SASA", "SISE", "SKBNK", "TAVHL", "TCELL", "THYAO", "TKFEN", "TOASO", "TSKB",
  "TTKOM", "TUKAS", "TUPRS", "ULKER", "VAKBN", "VESTL", "YKBNK", "ZOREN", "PGSUS", "ODAS",
  "MAVI", "ENJSA", "MPARK", "SOKM", "GESAN", "MAGEN", "CVKMD", "DSTKF", "BALSU", "ALTNY",
  "OYAKC", "AKGRT", "TTRAK", "KONTR", "EUPWR", "GENIL", "VESBE", "BJKAS", "KAYSE", "SMRTG",
  "AGROT", "YEOTK", "KLSER", "REEDR", "EGEEN", "CWENE", "QUAGR", "IZFAS", "ENERY", "GLRMK",
  "KOPOL", "GRTHO",
] as const;

export const YILDIZ_TICKERS = [
  "GARAN", "AKBNK", "BIMAS", "TCELL", "SAHOL", "ISCTR", "HALKB", "TUPRS", "KCHOL", "EREGL",
  "THYAO", "AEFES", "TAVHL", "YKBNK", "TTKOM", "CCOLA", "VAKBN", "ULKER", "ARCLK", "ENKAI",
  "TOASO", "SISE", "FROTO", "PETKM", "KRDMD", "TSKB", "KOZAL", "TTRAK", "ASELS", "PGSUS",
  "CIMSA", "TKFEN", "YAZIC", "DOAS", "AYGAZ", "MGROS", "TRKCM", "AKSA", "AKCNS", "DOHOL",
  "OTKAR", "NTHOL", "GUBRF", "DOCO", "SODA", "SKBNK", "AKFEN", "VESTL", "BOYP", "KRDMA",
  "AKSEN", "PNSUT", "KOZAA", "BAGFS", "ANHYT", "ECILC", "GOLTS", "ADANA", "AVISA", "ANSGR",
  "TATGD", "BRISA", "ALBRK", "BIZIM", "BJKAS", "GSDHO", "SARKY", "KARSN", "ALARK", "EGEEN",
  "KONYA", "SELEC", "BOLUC", "NETAS", "MRDIN", "FENER", "GOODY", "IPEKE", "KRDMB", "AKENR",
  "NUHCM", "GLYHO", "SASA", "AFYON", "ANACM", "IHLAS", "AKGRT", "LOGO", "PRKME", "BRSAN",
  "TEKST", "CLEBI", "TMSN", "KARTN", "ECZYT", "KORDS", "KOMHL", "ZOREN", "IZMDC", "GSRAY",
  "TRCAS", "PETUN", "ISFIN", "BUCIM", "ADEL", "METRO", "VESBE", "INDES", "ODAS", "CRFSA",
  "ISMEN", "KIPA", "BTCIM", "ALKIM", "DEVA", "ERBOS", "TKNSA", "NTTUR", "ALCTL",
] as const;

export const ANA_PAZAR_TICKERS = [
  "ASLAN", "EGSER", "BMEKS", "ITTFH", "HURGZ", "HEKTS", "VERUS", "BRYAT", "EGGUB", "PARSN",
  "ASUZU", "MNDRS", "ADESE", "CEMTS", "POLHO", "TBORG", "TSPOR", "IEYHO", "TIRE", "ANELE",
  "KRSTL", "ARSAN", "BFREN", "IHMAD", "AYEN", "BANVT", "RYSAS", "TURGG", "ADNAC", "ARENA",
  "ALCAR", "MEPET", "TUKAS", "ULUSE", "EUHOL", "AKSUE", "KUYAS", "GENTS", "UNYEC", "USAS",
  "IHEVA", "DYOBY", "YUNSA", "BSOKE", "GUSGR", "ULUUN", "KILER", "FINBN", "YATAS", "UYUM",
  "DGATE", "JANTS", "TEKTU", "IZOCM", "USAK", "CEMAS", "ROYAL", "ADBGR", "SANKO", "MRSHL",
  "LKMNH", "KLMSN", "CMBTN", "GEREL", "KATMR", "KUTPO", "MARTI", "ARMDA", "TUCLK", "FMIZP",
  "KNFRT", "SKTAS", "PENGD", "DGKLB", "BRKO", "KERVT", "DENCM", "ACSEL", "PRKAB", "IHYAY",
  "ATEKS", "DESPC", "ATPET", "FLAP", "KENT", "AKGUV", "EMKEL", "KAREL", "OLMIP", "SAYAS",
  "MAALT", "CRDFA", "YAYLA", "MAKTK", "DMSAS", "AVOD", "KRATL", "EDIP", "VAKKO", "ESCOM",
  "RTALB", "COMDO", "MIPAZ", "OSTIM", "IHGZT", "BOSSA", "BRKSN", "BLCYT", "BAKAB", "PKART",
  "DAGI", "ORGE", "YYAPI", "VAKFN", "DITAS", "BOYNR", "SNKRN", "PINSU", "GSDDE", "CMENT",
  "INTEM", "PRZMA", "ALYAG", "AVTUR", "SANEL", "TMPOL", "TGSAS", "SAMAT", "SILVR", "GARFA",
  "SANFM", "PSDTC", "BURCE", "DURDO", "GEDIK", "ALKA", "ANELT", "ARBUL", "MERKO", "BNTAS",
  "KRONT", "PIMAS", "HATEK", "EGCYH", "UTPYA", "GLRYH", "AKSEL", "DERIM", "GEDZA", "ERSU",
  "DAGHL", "DGZTE", "VKING", "CELHA", "SONME", "NIBAS", "ISBTR", "DESA", "DOGUB", "METUR",
  "DENIZ", "KLNMA", "OZBAL", "LINK", "PKENT", "BRMEN", "KAPLM", "AYCES", "EGPRO", "KRTEK",
  "BURVA", "ISKUR", "SEKFK", "INFO", "RAYSG", "DIRIT", "YAPRK", "LUKSK", "FFKRL", "SNPAM",
  "ULAS", "GLBMD", "OYLUM", "ISATR", "UNICO", "EMNIS", "BISAS", "LIDFA", "DOBUR", "HZNDR",
] as const;

export type SpotMarket = "bist100" | "yildiz" | "ana";

export const MARKET_LABELS: Record<SpotMarket, string> = {
  bist100: "BIST 100",
  yildiz: "Yıldız Pazar",
  ana: "Ana Pazar",
};

export const MARKET_ORDER: SpotMarket[] = ["bist100", "yildiz", "ana"];

export type SpotStock = {
  ticker: string;
  name: string;
  markets: SpotMarket[];
  referencePrice?: number;
};

const EXTRA_NAMES: Record<string, string> = {
  AKSA: "Aksa Akrilik",
  ANSGR: "Anadolu Sigorta",
  BRYAT: "Borusan Yatırım",
  BTCIM: "Batıçim",
  CCOLA: "Coca-Cola İçecek",
  ECILC: "Eczacıbaşı İlaç",
  FENER: "Fenerbahçe",
  GSRAY: "Galatasaray",
  TURSG: "Türkiye Sigorta",
  IPEKE: "İpek Enerji",
  ISMEN: "İş Yatırım",
  KOZAA: "Koza Anadolu",
  KOZAL: "Koza Altın",
  OTKAR: "Otokar",
  SARKY: "Sarkuysan",
  SKBNK: "Şekerbank",
  TUKAS: "Tukaş",
  ZOREN: "Zorlu Enerji",
  MAVI: "Mavi Giyim",
  MPARK: "MLP Sağlık",
  GESAN: "Girişim Elektrik",
  MAGEN: "Margün Enerji",
  CVKMD: "CVK Maden",
  DSTKF: "Destek Finans",
  BALSU: "Balsu Gıda",
  ALTNY: "Altınay Savunma",
  AKGRT: "Aksigorta",
  TTRAK: "Türk Traktör",
  KONTR: "Kontrolmatik",
  EUPWR: "Europower Enerji",
  GENIL: "Gen İlaç",
  VESBE: "Vestel Beyaz Eşya",
  BJKAS: "Beşiktaş",
  KAYSE: "Kayseri Şeker",
  SMRTG: "Smart Güneş",
  AGROT: "Agrotech",
  YEOTK: "Yeşil Otoyol",
  KLSER: "Kaleseramik",
  REEDR: "Reeder",
  EGEEN: "Ege Endüstri",
  CWENE: "CW Enerji",
  QUAGR: "Quadra Enerji",
  IZFAS: "İzfaş",
  ENERY: "Enerya",
  GLRMK: "Gülermak",
  KOPOL: "Kopol",
  GRTHO: "Grainturk Holding",
  YAZIC: "Yazıcılar Holding",
  AYGAZ: "Aygaz",
  TRKCM: "Trakya Cam",
  AKCNS: "Akçansa",
  NTHOL: "Net Holding",
  DOCO: "DO & CO",
  SODA: "Soda Sanayii",
  AKFEN: "Akfen Holding",
  BOYP: "Boyas",
  KRDMA: "Kardemir (A)",
  PNSUT: "Pınar Süt",
  BAGFS: "Bagfaş",
  ANHYT: "Anadolu Hayat",
  GOLTS: "Göltaş Çimento",
  ADANA: "Adana Çimento",
  AVISA: "AgeSA",
  TATGD: "Tat Gıda",
  BRISA: "Brisa",
  ALBRK: "Albaraka Türk",
  BIZIM: "Bizim Toptan",
  GSDHO: "GSD Holding",
  KARSN: "Karsan",
  KONYA: "Konya Çimento",
  SELEC: "Selçuk Ecza",
  BOLUC: "Bolü Çimento",
  NETAS: "Netaş",
  MRDIN: "Mardin Çimento",
  GOODY: "Goodyear",
  KRDMB: "Kardemir (B)",
  AKENR: "Akenerji",
  NUHCM: "Nuh Çimento",
  GLYHO: "Global Yatırım",
  AFYON: "Afyon Çimento",
  ANACM: "Anadolu Cam",
  IHLAS: "İhlas Holding",
  LOGO: "Logo Yazılım",
  PRKME: "Park Elektrik",
  TEKST: "Tek-Art Turizm",
  CLEBI: "Çelebi",
  TMSN: "Tümosan",
  KARTN: "Kartonsan",
  ECZYT: "Eczacıbaşı Yatırım",
  KORDS: "Kordsa",
  KOMHL: "Komili Holding",
  IZMDC: "İzmir Demir Çelik",
  TRCAS: "Turcas Petrol",
  PETUN: "Pınar Et ve Un",
  ISFIN: "İş Finansal Kiralama",
  BUCIM: "Bursa Çimento",
  ADEL: "Adel Kalemcilik",
  METRO: "Metro Holding",
  INDES: "Index Grup",
  CRFSA: "CarrefourSA",
  KIPA: "Kipa",
  ALKIM: "Alkim Kimya",
  DEVA: "Deva Holding",
  ERBOS: "Erbosan",
  TKNSA: "Teknosa",
  NTTUR: "Net Turizm",
  ALCTL: "Alcatel Teletaş",
  ASLAN: "Aslan Çimento",
  EGSER: "Ege Seramik",
  BMEKS: "Bimeks",
  ITTFH: "İttifak Holding",
  HURGZ: "Hürriyet",
  VERUS: "Verusa Holding",
  EGGUB: "Ege Gübre",
  PARSN: "Parsan",
  ASUZU: "Anadolu Isuzu",
  MNDRS: "Menderes Tekstil",
  ADESE: "Adese",
  CEMTS: "Çemtaş",
  POLHO: "Polisan Holding",
  TBORG: "Tuborg",
  TSPOR: "Trabzonspor",
  IEYHO: "Işıklar Enerji",
  TIRE: "Tire Kutsan",
  ANELE: "Anel Elektrik",
  KRSTL: "Kristal Kola",
  ARSAN: "Arsan Tekstil",
  BFREN: "Bosch Fren Sistemleri",
  IHMAD: "İhlas Madencilik",
  AYEN: "Ayen Enerji",
  BANVT: "Banvit",
  RYSAS: "Reysaş",
  TURGG: "Türker Proje",
  ADNAC: "Adana Çimento (C)",
  ARENA: "Arena Bilgisayar",
  ALCAR: "Alarko Carrier",
  MEPET: "Mepet",
  ULUSE: "Ulusoy Elektrik",
  EUHOL: "Euro Yatırım Holding",
  AKSUE: "Aksu Enerji",
  KUYAS: "Kuyas Yatırım",
  GENTS: "Gentel",
  UNYEC: "Ünye Çimento",
  USAS: "Uşak Seramik",
  IHEVA: "İhlas Ev Aletleri",
  DYOBY: "Dyo Boya",
  YUNSA: "Yünsa",
  BSOKE: "Batısöke Çimento",
  GUSGR: "Güneş Sigorta",
  ULUUN: "Ulusoy Un",
  KILER: "Kiler GYO",
  FINBN: "QNB Finansbank",
  YATAS: "Yataş",
  UYUM: "Uyum Gıda",
  DGATE: "Datagate",
  JANTS: "Jantsa",
  TEKTU: "Tek-Art Turizm",
  IZOCM: "İzocam",
  USAK: "Uşak Seramik",
  CEMAS: "Çemaş",
  ROYAL: "Royal Halı",
  ADBGR: "Adel",
  SANKO: "Sanko Pazarlama",
  MRSHL: "Marshall",
  LKMNH: "Lokman Hekim",
  KLMSN: "Klimasan",
  CMBTN: "Çimbeton",
  GEREL: "Gersan",
  KATMR: "Katmerciler",
  KUTPO: "Kütahya Porselen",
  MARTI: "Martı Otel",
  ARMDA: "Armada",
  TUCLK: "Tuğçelik",
  FMIZP: "Federal-Mogul İzmit",
  KNFRT: "Konfrut",
  SKTAS: "Söktaş",
  PENGD: "Penguen Gıda",
  DGKLB: "Doğusan",
  BRKO: "Birko",
  KERVT: "Kerevitaş",
  DENCM: "Denizli Cam",
  ACSEL: "Acıselsan",
  PRKAB: "Türk Prysmian Kablo",
  IHYAY: "İhlas Yayın Holding",
  ATEKS: "Akın Tekstil",
  DESPC: "Despec",
  ATPET: "ATP",
  FLAP: "Flap Kongre",
  KENT: "Kent Gıda",
  AKGUV: "Akgüven",
  EMKEL: "Emek Elektrik",
  KAREL: "Karel",
  OLMIP: "Olmuhsan",
  SAYAS: "Say Yenilenebilir",
  MAALT: "Marmaris Altınyunus",
  CRDFA: "Creditwest Faktoring",
  YAYLA: "Yayla Enerji",
  MAKTK: "Makina Takım",
  DMSAS: "Demisaş",
  AVOD: "A.V.O.D.",
  KRATL: "Körfez",
  EDIP: "Edip Gayrimenkul",
  VAKKO: "Vakko",
  ESCOM: "Escort Teknoloji",
  RTALB: "RTA Laboratuvarları",
  COMDO: "Componenta",
  MIPAZ: "Milpa",
  OSTIM: "Ostim Endüstriyel",
  IHGZT: "İhlas Gazetecilik",
  BOSSA: "Bossa",
  BRKSN: "Berkosan",
  BLCYT: "Bilici Yatırım",
  BAKAB: "Bak Ambalaj",
  PKART: "Plastikkart",
  DAGI: "Dagi Giyim",
  ORGE: "Orge Enerji",
  YYAPI: "Yeşil Yapı",
  VAKFN: "Vakıf Menkul",
  DITAS: "Ditaş Doğan",
  BOYNR: "Boyner",
  SNKRN: "Sanko",
  PINSU: "Pınar Su",
  GSDDE: "GSD Denizcilik",
  CMENT: "Çimentaş",
  INTEM: "İntema",
  PRZMA: "Prizma",
  ALYAG: "Altınyağ",
  AVTUR: "Avrasya Petrol",
  SANEL: "Sanel Mühendislik",
  TMPOL: "Temapol",
  TGSAS: "TGS Dış Ticaret",
  SAMAT: "Saray Matbaacılık",
  SILVR: "Silverline",
  GARFA: "Garanti Faktoring",
  SANFM: "Sanifoam",
  PSDTC: "Pergamon",
  BURCE: "Burçelik",
  DURDO: "Duran Doğan",
  GEDIK: "Gedik Yatırım",
  ALKA: "Alkim Kağıt",
  ANELT: "Anel Telekom",
  ARBUL: "Arbul",
  MERKO: "Merko Gıda",
  BNTAS: "Bantaş",
  KRONT: "Kron Telekomünikasyon",
  PIMAS: "Pimaş",
  HATEK: "Hateks",
  EGCYH: "Ege Ceyl",
  UTPYA: "Utopya",
  GLRYH: "Güler Yatırım Holding",
  AKSEL: "Aksel",
  DERIM: "Derimod",
  GEDZA: "Gediz Ambalaj",
  ERSU: "Ersu Gıda",
  DAGHL: "Dagi Holding",
  DGZTE: "Doğu Zirai",
  VKING: "Viking Kağıt",
  CELHA: "Çelik Halat",
  SONME: "Sönmez Filament",
  NIBAS: "Niğbaş",
  ISBTR: "İş Bankası (B)",
  DESA: "Desa Deri",
  DOGUB: "Doğusan",
  METUR: "Metemtur",
  DENIZ: "Denizbank",
  KLNMA: "Kale Madencilik",
  OZBAL: "Özbal",
  LINK: "Link Bilgisayar",
  PKENT: "Petrokent",
  BRMEN: "Birleşik Menkul",
  KAPLM: "Kaplamin",
  AYCES: "Altın Yunus Çeşme",
  EGPRO: "Ege Profil",
  KRTEK: "Karsu Tekstil",
  BURVA: "Burçelik Vana",
  ISKUR: "İş GYO",
  SEKFK: "Şeker Faktoring",
  INFO: "Info Yatırım",
  RAYSG: "Ray Sigorta",
  DIRIT: "Diriteks",
  YAPRK: "Yaprak Süt",
  LUKSK: "Lüks Kadife",
  FFKRL: "Federal-Mogul",
  SNPAM: "Sönmez Pamuklu",
  ULAS: "Ulaşlar Turizm",
  GLBMD: "Global Menkul",
  OYLUM: "Oylum Sınai",
  ISATR: "İş Bankası (A)",
  UNICO: "Unico Sigorta",
  EMNIS: "Eminiş Ambalaj",
  BISAS: "Bisaş",
  LIDFA: "Lider Faktoring",
  DOBUR: "Doğan Burda",
  HZNDR: "Huzur Deterjan",
};

const viopPay = new Map(
  CONTRACTS.filter((c) => c.group === "pay").map((c) => [c.ticker, c]),
);

function nameOf(ticker: string): string {
  return EXTRA_NAMES[ticker] ?? viopPay.get(ticker)?.name ?? ticker;
}

export const SPOT_STOCKS: SpotStock[] = (() => {
  const markets = new Map<string, Set<SpotMarket>>();
  const add = (tickers: readonly string[], market: SpotMarket) => {
    for (const ticker of tickers) {
      const set = markets.get(ticker) ?? new Set<SpotMarket>();
      set.add(market);
      markets.set(ticker, set);
    }
  };
  add(BIST100_TICKERS, "bist100");
  add(YILDIZ_TICKERS, "yildiz");
  add(ANA_PAZAR_TICKERS, "ana");

  return [...markets.entries()]
    .map(([ticker, set]) => ({
      ticker,
      name: nameOf(ticker),
      markets: MARKET_ORDER.filter((m) => set.has(m)),
      referencePrice: viopPay.get(ticker)?.price,
    }))
    .sort((a, b) => a.ticker.localeCompare(b.ticker, "tr"));
})();

export function searchSpotStocks(
  query: string,
  market?: SpotMarket | "all",
): SpotStock[] {
  const pool =
    !market || market === "all"
      ? SPOT_STOCKS
      : SPOT_STOCKS.filter((s) => s.markets.includes(market));
  const q = query.trim().toLocaleLowerCase("tr-TR");
  if (!q) return pool;
  return pool.filter((s) => {
    return (
      s.ticker.toLocaleLowerCase("tr-TR").includes(q) ||
      s.name.toLocaleLowerCase("tr-TR").includes(q) ||
      s.markets.some((m) => MARKET_LABELS[m].toLocaleLowerCase("tr-TR").includes(q))
    );
  });
}
